### PR TITLE
Image Upload

### PR DESCRIPTION
**Pull request by cubap**

### CODE REVIEW

**Comment by cubap** [comment]
`getAllJPGsRecursive(dir)` should be okay with <kbd>.JPG</kbd> extensions... This may need testing.

```java
public static Stack<File> getJPGSInFolder(File dir) {
      Stack<File> res = new Stack();
      File[] allFiles = dir.listFiles();
        for (File allFile : allFiles) {
            if (allFile.getName().toLowerCase().contains(".jpg")) {
                res.add(allFile);
            } else {
                if (allFile.isDirectory()) {
                    res = merge(res, getJPGSInFolder(allFile));
                }
            }
        }
      return res;
   }
```

**Comment by cubap** [comment]
Look in logs for `out.print("bad image " + images[i].getName() + ", would do something\n");` if there are still files that aren't jpgs getting saved.

**Comment by cubap** [comment]
@thehabes This isn't implemented, but it builds and shows no errors.

**Comment by cubap** [comment]
`UserImageCollection.delete(m)` is never used, but it probably should be considered for use in a cleanup method.

**Comment by thehabes** [comment]
Ok looks good, I am going to bring it in and deploy for testing

**Comment by cubap** [comment]
It should avoid breaking on `File Names.jpg` allow for `img.JPG` and `iMG.jpeg` and even `img.jPg` for that matter. There is a separate step in folio creation that validates it is a readable jpg, so this shouldn't break anything else.

It does not attempt to resolve any issues in the autoparsing or other initializations of this MS.

**Comment by thehabes** [comment]
Good, this should just focus on the private image stuff.  I will test uploading the .zip on this branch.  If all is well, then this should be a real PR so I can pull it in and work on my branch with these images.

While testing that branch, if there are any private image issues, I will look to you for hotfixes.

**Comment by thehabes** [comment]
I tested this against the production data brought over to dev for the following problematic projects

http://tpentest.rerum.io/TPEN/transcription.html?projectID=6646
http://tpentest.rerum.io/TPEN/transcription.html?projectID=6739
http://tpentest.rerum.io/TPEN/transcription.html?projectID=6763

There are no private image errors like there were before, no Broken Pipes.

**Review by thehabes — APPROVED** [review]

**Pull request merged**
