### PR TITLE
renaming cnt:chars to chars in resource map, closes #643

### LINKED ISSUE #643: Presentation API Validation
The Presentation API 2 version of the Manifests are not passing the validator http://presentation-validator.iiif.io/.  If it is within the scope of a task, track these errors down and fix them so that your resources make it through validation.  This is important for the client, and the main reason you are working on this.

- The error as of 10/20/2022 is `Validation Error: cnt:ContentAsText['chars'] not present and required`

### PR DESCRIPTION
**Pull request by markskroba**

### CODE REVIEW

**Comment by markskroba** [comment]
This seems like an obvious fix - however, it looks like we have no way to test it since our manifests have no canvases attached to them

**Review by Woodlnsoul — COMMENTED** [review]
Looks pretty straight forward to me!

**Review by thehabes — CHANGES_REQUESTED** [review]
If you are fixing this for the Presentation API 2 stuff, this is a breaking change.  My applications (like T-PEN, see `transcribe.js` ) use script to get lines like `var rawLineText = line.resource["cnt:chars"];`  When this change goes live, my applications will no longer find the line text.

If you are anticipating this for Presentation API 3 Web Annotations, know that `cnt:chars` and `chars` are no longer involved.

Please revert this change, or re-do it in a way that isn't a breaking change.  My preference is to close this PR without accepting it and letting it be.  If you would like to keep a note of this for the app, you can make an issue for it.

**Comment by tvay11** [comment]
chars will not work for any code that requires cnt:chars.

**Pull request closed without merging**
