### PR TITLE
Real URIs for images

### PR DESCRIPTION
**Pull request by cubap**

### CODE REVIEW

**Comment by thehabes** [comment]
This branch is deployed at http://tpentest.rerum.io/TPEN/

**Comment by cubap** [comment]
@thehabes Can you redeploy this? I found that the export for private images was placing "file://" URIs in it, which it may be doing on TPEN as well, but we can fix it with the `pageImage` servlet.

**Comment by thehabes** [comment]
Backed up current deployed version to my dev $~home folder. 

Pulled down Exporting real image URLs branch.  

Built and Redeployed at tpentest.

**Comment by cubap** [comment]
All behavior that I tested on dev seems to be working, but there is a quirky thing happening in some cases that I am about to chase down.

When going to a page that hasn't been loaded, I get the error "No image for this canvas or it could not be resolved.  Not drawing lines." and then after a moment the page loads with terrible parsing. In the classic interface, there is no error, but the parsing matches.

**Comment by cubap** [comment]
I think this is ready. There are a few issues #528 and #530 that I ticketed that are not related to my changes. I would be comfortable with this up live (with appropriate backup measures in place).

**Pull request merged**
